# PaCo-2 Configuration for EfficientNet-B3 backbone

# Inherit from base
_base_: "ufg_base.yaml"

# Override model settings  
model:
  backbone: "efficientnet_b0"

# Adjust for different input size
data:
  image_size: 300   # EfficientNet-B0 native size
  batch_size: 24    # Smaller batch for larger images

optimizer:
  lr: 8.0e-4        # Lower LR for larger model
