# PaCo-2 Fast Training Configuration for UFGVC
# Optimized for faster training with reduced complexity

# Dataset configuration
dataset:
  name: "cotton80"
  root: "./data"
  download: true

# Data processing configuration
data:
  image_size: 224
  batch_size: 64      # Larger batch size for better GPU utilization
  num_workers: 8      # More workers for faster data loading

# Model configuration
model:
  backbone: "resnet50"
  pretrained: true
  
  # Reduced part sampling for faster computation
  K: 2            # Reduced from 4 to 2 parts
  r: 3            # Reduced window size from 5 to 3
  d: 32           # Reduced dimension from 64 to 32
  
  # Loss weights
  lambda_pac: 0.5   # Reduced PaC loss weight
  eta_soc: 0.05     # Reduced SoC loss weight
  alpha: 0.2
  beta: 0.02        # Reduced prototype regularization
  gamma: 0.05       # Reduced weighted CE factor
  
  # Technical parameters
  epsilon: 1.0e-5
  tau: 1.0e-5
  metric: "fro"
  
  # Disable some complex features for speed
  use_mahalanobis_warmup: false  # Disable warmup for simplicity
  warmup_epochs: 0
  use_weighted_ce: false         # Disable weighted CE
  use_semi_hard: false           # Disable semi-hard mining
  use_class_proto: false         # Disable class prototypes
  proto_momentum: 0.9

# Optimizer configuration
optimizer:
  name: "adamw"
  lr: 2.0e-3        # Higher learning rate
  weight_decay: 1.0e-4

# Learning rate scheduler
scheduler:
  use_scheduler: true
  name: "cosine"
  T_max: 50         # Shorter training
  eta_min: 1.0e-6

# Training configuration
training:
  epochs: 50        # Reduced epochs for testing
  seed: 3407
  save_dir: "./runs"
  print_freq: 25    # Print every 25 batches

# Evaluation settings
evaluation:
  save_confusion_matrix: false  # Skip to save time
  save_embeddings: false        # Skip to save time
  compute_fisher_ratio: false   # Skip to save time
